image: openjdk:8

variables:
  APP_NAME: 'cdp-file-downloader'
  FTP_DIR: "/nfs/ftp/pub/databases/covid19dataportal/"


stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  tags:
    - dcap-gitlab-runner-covid19
  script:
    - chmod u+x gradlew
    - ./gradlew clean test

build_prod:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/dist/${APP_NAME}.zip
  tags:
    - dcap-gitlab-runner-covid19
  only:
    - master

deploy_prod:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    - chmod u+x build/dist/${APP_NAME}.zip
    - scp -o StrictHostKeyChecking=no build/dist/${APP_NAME}.zip covidftpwriter@noah-login-01.ebi.ac.uk:${FTP_DIR}
  dependencies:
    - build_prod
  when: manual
  tags:
    - dcap-gitlab-runner-covid19
  only:
    - master