image: openjdk:8

variables:
  APP_VERSION: "1.1.10"
  APP_NAME: 'ena-file-downloader'
  FTP_DIR: "/nfs/ftp/public/databases/ena/tools"
  APP_NAME_VERSION: ${APP_NAME}-${APP_VERSION}.zip
  FTP_STG_DIR: "/nfs/production/cochrane/ena/ftp-staging/tools"

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=.gradle
  tags:
    - dcap-gitlab-runner
  script:
    - chmod u+x gradlew
    - ./gradlew clean test

build_prod:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=.gradle
  script:
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/dist/${APP_NAME_VERSION}
  tags:
    - dcap-gitlab-runner
  #only:
  #  - master

deploy_prod:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$CODON_DATALIB_SSH_PVT_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - chmod u+x build/dist/${APP_NAME_VERSION}
    - scp -o StrictHostKeyChecking=no build/dist/${APP_NAME_VERSION} datalib@codon-login-01.ebi.ac.uk:${FTP_STG_DIR}
    - ssh datalib@codon-login-01.ebi.ac.uk "sbatch --mem 1G -t 3:00:00 -p datamover -W --wrap=\"cd ${FTP_STG_DIR} && find . -type f -name 'ena-file-downloader-*' -not -name ${APP_NAME_VERSION} -delete\""
    - ssh datalib@codon-login-01.ebi.ac.uk "sbatch --mem 1G -t 3:00:00 -p datamover -W --wrap=\"rsync -avt --include=${APP_NAME_VERSION} --exclude=\"*\" --exclude=\"ena-file-downloader-*\" --delete-excluded ${FTP_STG_DIR}/ ${FTP_DIR}/\""
    - ssh datalib@codon-login-01.ebi.ac.uk "sbatch --mem 1G -t 3:00:00 -p datamover -W --wrap=\"cd ${FTP_DIR} && ln -sf ${APP_NAME_VERSION} ${APP_NAME}.zip\""
  dependencies:
    - build_prod
  when: manual
  tags:
    - dcap-gitlab-runner
  #only:
  #  - master
