image: openjdk:8

variables:
  APP_VERSION: "0.0.2"
  APP_NAME: 'ena-file-downloader'
  FTP_DIR: "/nfs/ftp/pub/databases/ena/tools"


stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

#test:
#  stage: test
#  before_script:
#    - export GRADLE_USER_HOME=`pwd`/.gradle
#  tags:
#    - dcap-gitlab-runner
#  script:
#    - chmod u+x gradlew
#    - ./gradlew clean test

test:
  stage: test
  before_script:
    - export GRADLE_USER_HOME=command-line-downloader/.gradle
  tags:
    - dcap-gitlab-runner
  script:
    - command-line-downloader/./gradlew clean build -x test

build_prod:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=command-line-downloader/.gradle
  script:
    - command-line-downloader/./gradlew clean build -x test
  artifacts:
    paths:
      - command-line-downloader/build/dist/${APP_NAME}-${APP_VERSION}.zip
  tags:
    - dcap-gitlab-runner
  only:
    - master

deploy_prod:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    - chmod u+x command-line-downloader/build/dist/${APP_NAME}-${APP_VERSION}.zip
    - scp -o StrictHostKeyChecking=no command-line-downloader/build/dist/${APP_NAME}-${APP_VERSION}.zip datalib@noah-login-01.ebi.ac.uk:${FTP_DIR}
    - ssh datalib@noah-login-01.ebi.ac.uk "ln -sf ${FTP_DIR}/${APP_NAME}-${APP_VERSION}.zip ${FTP_DIR}/${APP_NAME}.zip"
  dependencies:
    - build_prod
  when: manual
  tags:
    - dcap-gitlab-runner
  only:
    - master
